import "@radix-ui/themes/styles.css";
import "./globals.css";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "./Navbar";
import { Container, Theme } from "@radix-ui/themes";
import QueryClientProvider from "./QueryClientProvider";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata: Metadata = {
  title: "ssr-editor",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.variable}>
        <QueryClientProvider>
          <Theme accentColor="gray">
            <Navbar />

            <main className="p-5">
              <Container> {children} </Container>
            </main>
          </Theme>
        </QueryClientProvider>
      </body>
    </html>
  );
}
