import "@radix-ui/themes/styles.css";
import "./globals.css";
import type { Metadata } from "next";
import Navbar from "./Navbar";
import { Theme } from "@radix-ui/themes";
import QueryClientProvider from "./QueryClientProvider";
import { Inter } from "next/font/google";
import { AuthProvider } from "./AuthContext";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata: Metadata = {
  title: "ssr-editor",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.variable}>
        <QueryClientProvider>
          <AuthProvider>
            <Theme accentColor="gray">
              <Navbar />

              <main className="p-5">{children}</main>
            </Theme>
          </AuthProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
